// <auto-generated />
namespace Ornaments.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class productidInFeedBack : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productidInFeedBack));
        
        string IMigrationMetadata.Id
        {
            get { return "202005200908521_productidInFeedBack"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
