// <auto-generated />
namespace Ornaments.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TransactionNumberAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TransactionNumberAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202006221506215_TransactionNumber Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
